# This is a config for E2B sandbox template.
# You can use template ID (ocbsci17eksx82hpxc64) or template name (lovable-clone-purplemerit) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-clone-purplemerit") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-clone-purplemerit") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-clone-purplemerit')

team_id = "19b17b9e-d31d-42fa-8014-ec7c227a3d57"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-clone-purplemerit"
template_id = "ocbsci17eksx82hpxc64"
